import type { Project, Unit } from "./data";

const sourceRoot = "https://drive.google.com/drive/folders/1FlJrY5kvQhYpxebvE3rBJr2O78KSMJfI";
const collectionUpdatedAt = "2026-04-22";
const image = (id: string) => `https://lh3.googleusercontent.com/d/${id}=w1600`;

export const avanzaProjects: Project[] = [
  {
    id: "avanza-unico",
    name: "UNICO",
    developer: "Grupo Avanza",
    location: "Av. Felipe Molas López, Asunción",
    stage: "Terminado",
    delivery: "Entrega inmediata — confirmar disponibilidad final",
    confidence: "Requiere confirmación",
    updatedAt: collectionUpdatedAt,
    summary: "Seis unidades publicadas con precio en The Collection. La fuente no identifica tipología, superficie ni cochera; esos campos se excluyen de los filtros hasta su confirmación.",
    brochure: "",
    priceList: "https://drive.google.com/drive/folders/10kCQDtpTYVrdXTTaJv8F5qzpt9MTjKnh",
    mediaFolder: "https://drive.google.com/drive/folders/10kCQDtpTYVrdXTTaJv8F5qzpt9MTjKnh",
    driveFolder: sourceRoot,
    imageUrl: image("1KKHtFcMTNH43wjqtTN9NoyuRVrq7Uq2K"),
    mapQuery: "Edificio UNICO Avenida Felipe Molas Lopez Asuncion Paraguay",
    color: "#263e69",
  },
  {
    id: "avanza-in-1362",
    name: "IN 1362 Molas",
    developer: "Grupo Avanza",
    location: "Av. Dr. Felipe Molas López 1362, Asunción",
    stage: "Terminado",
    delivery: "Entrega inmediata — confirmar disponibilidad final",
    confidence: "Requiere confirmación",
    updatedAt: collectionUpdatedAt,
    summary: "Unidad 1302 publicada como disponible en The Collection. El precio y la tipología están respaldados; superficie y cochera requieren confirmación final.",
    brochure: "",
    priceList: "https://drive.google.com/drive/folders/1JzKwP6b59iT0HD_ugCrMjobv51uK6__e",
    mediaFolder: "https://drive.google.com/drive/folders/1JzKwP6b59iT0HD_ugCrMjobv51uK6__e",
    driveFolder: sourceRoot,
    imageUrl: image("16mET_kUn4VZ0QRYjeEAc1Q2sYOH_-tcO"),
    mapQuery: "IN 1362 Molas Asuncion Paraguay",
    color: "#5d786d",
  },
  {
    id: "avanza-houze",
    name: "HOUZE",
    developer: "Grupo Avanza",
    location: "Las Lomas, Asunción",
    stage: "Terminado",
    delivery: "Entrega inmediata — confirmar disponibilidad final",
    confidence: "Requiere confirmación",
    updatedAt: collectionUpdatedAt,
    summary: "Tres monoambientes publicados como disponibles en The Collection, con fotografías reales y precio por unidad. La superficie y cochera deben confirmarse antes de cotizar.",
    brochure: "",
    priceList: "https://drive.google.com/drive/folders/12UJ9BV372o47VjvvXWKNDNFcDc1zfAvT",
    mediaFolder: "https://drive.google.com/drive/folders/12UJ9BV372o47VjvvXWKNDNFcDc1zfAvT",
    driveFolder: sourceRoot,
    imageUrl: image("1KVsGphbHbRgA3XDXldEG-JvC4sfoNTdX"),
    mapQuery: "Edificio Houze Las Lomas Asuncion Paraguay",
    color: "#725b49",
  },
  {
    id: "avanza-well",
    name: "WELL",
    developer: "Grupo Avanza",
    location: "Asunción — ubicación exacta por confirmar",
    stage: "Requiere confirmación",
    delivery: "Requiere confirmación",
    confidence: "Requiere confirmación",
    updatedAt: "2025-09-01",
    summary: "Brochure y fotografías disponibles. No se encontró una lista oficial vigente de precios y disponibilidad; por seguridad no se muestran unidades en el buscador.",
    brochure: "https://drive.google.com/file/d/19cOfpEGjBDT3aN_9nA81CZ_nUIhr_-me/view",
    mediaFolder: "https://drive.google.com/drive/folders/1qERjYM6jmNo4YKHYw7snf3zfWk4bN4Wm",
    driveFolder: sourceRoot,
    imageUrl: image("1m1W3NeJT5NgwxYG-_PtDxbG1DsXAhw5a"),
    mapQuery: "Avanza WELL Asuncion Paraguay",
    color: "#7f8a7b",
  },
  {
    id: "avanza-viwwo",
    name: "VIWWO",
    developer: "Grupo Avanza",
    location: "Eje San Martín, Asunción",
    stage: "Requiere confirmación",
    delivery: "Requiere confirmación",
    confidence: "Requiere confirmación",
    updatedAt: "2026-08-06",
    summary: "Brochure, renders y videos verificados. El proyecto contempla estudios de 26 a 41 m², unidades de 1 dormitorio de 39 a 45 m² y unidades de 2 dormitorios de 71 a 79 m². Falta la disponibilidad comercial vigente.",
    brochure: "https://drive.google.com/file/d/11wZjH7a8eZ846fiNfYFM6631msdhXF9-/view",
    plansFolder: "https://drive.google.com/drive/folders/1qDB7LpxzlRbuXczYnKxtCZC_0OoXdUYM",
    mediaFolder: "https://drive.google.com/drive/folders/1Hh7_e4-ONIvs7RhtbX-qkf7_7Y34F7qR",
    videoFolder: "https://drive.google.com/drive/folders/10k1BCksV4myCP8k7_Lvp6dIG4Xf6DBG0",
    driveFolder: "https://drive.google.com/drive/folders/1XvAHuj5jvV8wAfx4zbcecKTiCZknBk1l",
    imageUrl: image("156nav8OA8wJSjlpJ3B_E32CdZ4wH3OQq"),
    mapQuery: "VIWWO Avenida San Martin Asuncion Paraguay",
    color: "#394e62",
  },
  {
    id: "avanza-nest",
    name: "NEST Living",
    developer: "Grupo Avanza",
    location: "Asunción — ubicación exacta por confirmar",
    stage: "Requiere confirmación",
    delivery: "Requiere confirmación",
    confidence: "Requiere confirmación",
    updatedAt: "2026-05-18",
    summary: "Proyecto de 15 pisos, 122 unidades y 11 amenities. Hay brochure, renders, fotos del modelo y videos, pero no una lista oficial de unidades disponibles y precios.",
    brochure: "https://drive.google.com/file/d/1f4rRRfCPWKp0geTx6y1QKM8VYPTf7uqR/view",
    plansFolder: "https://drive.google.com/drive/folders/1bT5yh6M1MkRXl8j5ibjFuRXW_Uw9LZyf",
    mediaFolder: "https://drive.google.com/drive/folders/1nY2zi5EYNYTgRRwQEbMUdP2DQhUDLWMt",
    videoFolder: "https://drive.google.com/drive/folders/10Wb_79ilGggJTnJCYv5APDt5EUDm-t33",
    driveFolder: "https://drive.google.com/drive/folders/1ryabwYOKK0jz-hKSxjCJfL85iNT5XcbW",
    imageUrl: image("1HwT-ek1YR1EqXB3E_iTmlijyGcyaS7Ka"),
    mapQuery: "NEST Living Avanza Asuncion Paraguay",
    color: "#9d7453",
  },
  {
    id: "avanza-aura",
    name: "AURA",
    developer: "Grupo Avanza",
    location: "Argüello y Quesada, Asunción",
    stage: "Requiere confirmación",
    delivery: "Requiere confirmación",
    confidence: "Requiere confirmación",
    updatedAt: "2026-05-18",
    summary: "Brochure con estudios de 31–32 m², departamentos de 1 dormitorio de 33–45 m² y unidades de 2 dormitorios de 71 m². Faltan precios y disponibilidad oficial vigente.",
    brochure: "https://drive.google.com/file/d/1ZhIbskDjp38iZHR-BBwq3GSF46qaAR_1/view",
    plansFolder: "https://drive.google.com/drive/folders/1RspL5NBJ_5qkfegSpAdVpaalJcPo6uD9",
    mediaFolder: "https://drive.google.com/drive/folders/1LPCPqd7OQ7q7o_GO7dtavm45p3Uh3Ry0",
    videoFolder: "https://drive.google.com/drive/folders/1dFPyrWOZHHTIhV427NXZhA9Hewo7WaxT",
    driveFolder: "https://drive.google.com/drive/folders/1v7WFDEeYjksicxcfpKWeF9Q42ioNYSAv",
    imageUrl: image("1aHgaSylUO2IThU3kRj1KGUIgwYTwpT4o"),
    mapQuery: "AURA Argüello Quesada Asuncion Paraguay",
    color: "#ad805f",
  },
  {
    id: "avanza-harbor",
    name: "HARBOR",
    developer: "Grupo Avanza",
    location: "Avenida del Yacht, Lambaré",
    stage: "Pozo",
    delivery: "Requiere confirmación",
    confidence: "Requiere confirmación",
    updatedAt: "2026-08-05",
    summary: "Condominio cerrado de 20 casas desde 127 m² construidos, lote promedio de 127 m² y dos cocheras. El plano comercial no permite confirmar qué casas siguen libres; no se cargan unidades sin una lista vigente.",
    brochure: "https://drive.google.com/file/d/1H0dzQMh1bAVloS1Klto1OMLoY9DU2DMt/view",
    plansFolder: "https://drive.google.com/drive/folders/1fSTLjcLON99qmsfRIj8rS3jXRwPU08Z0",
    mediaFolder: "https://drive.google.com/drive/folders/1YF0syIm9FAZsDTri_tfbDA4TlMeTP0aY",
    videoFolder: "https://drive.google.com/drive/folders/1tKyP-Bv0Z5i0OKrQzn4Sbsd7-wkR2RHr",
    driveFolder: "https://drive.google.com/drive/folders/1t3J3MQFFPiLKBdMFl91P3JaB_PdaooHh",
    imageUrl: image("1CJyUyAeyaaqAyM8a5KgqZihHvnMUm5Zd"),
    mapQuery: "HARBOR Avenida del Yacht Lambare Paraguay",
    color: "#47788b",
  },
];

const staleAvailability = [
  "Disponibilidad publicada en abril de 2026; confirmar antes de cotizar",
  "Precio sujeto a reconfirmación",
];

export const avanzaUnits: Unit[] = [
  { id: "avanza-unico-1303", projectId: "avanza-unico", code: "1303", floor: "13", type: "Tipología a confirmar", bedrooms: -1, ownM2: 0, balconyM2: 0, totalM2: 0, currency: "USD", price: 65500, parking: -1, status: "Disponible", features: [...staleAvailability, "Tipología, superficie y cochera pendientes"], updatedAt: collectionUpdatedAt, imageUrl: image("1KKHtFcMTNH43wjqtTN9NoyuRVrq7Uq2K") },
  { id: "avanza-unico-1203", projectId: "avanza-unico", code: "1203", floor: "12", type: "Tipología a confirmar", bedrooms: -1, ownM2: 0, balconyM2: 0, totalM2: 0, currency: "USD", price: 65100, parking: -1, status: "Disponible", features: [...staleAvailability, "Tipología, superficie y cochera pendientes"], updatedAt: collectionUpdatedAt, imageUrl: image("15YNeJD5Brqw2mLwo-y4MqfevpWWkHqLE") },
  { id: "avanza-unico-1006", projectId: "avanza-unico", code: "1006", floor: "10", type: "Tipología a confirmar", bedrooms: -1, ownM2: 0, balconyM2: 0, totalM2: 0, currency: "USD", price: 63550, parking: -1, status: "Disponible", features: [...staleAvailability, "Tipología, superficie y cochera pendientes"], updatedAt: collectionUpdatedAt, imageUrl: image("1cl_0808Fi5h0flSEh7nWEfjR4qw1Wpa_") },
  { id: "avanza-unico-1205", projectId: "avanza-unico", code: "1205", floor: "12", type: "Tipología a confirmar", bedrooms: -1, ownM2: 0, balconyM2: 0, totalM2: 0, currency: "USD", price: 61700, parking: -1, status: "Disponible", features: [...staleAvailability, "Tipología, superficie y cochera pendientes"], updatedAt: collectionUpdatedAt, imageUrl: image("1q-gVTyjKYMiKwUlUcV9kT4Sb1TcX26sS") },
  { id: "avanza-unico-1005", projectId: "avanza-unico", code: "1005", floor: "10", type: "Tipología a confirmar", bedrooms: -1, ownM2: 0, balconyM2: 0, totalM2: 0, currency: "USD", price: 60900, parking: -1, status: "Disponible", features: [...staleAvailability, "Tipología, superficie y cochera pendientes"], updatedAt: collectionUpdatedAt, imageUrl: image("1on49hYn-7nxbAEn6zGdTkmS3xLlULFmo") },
  { id: "avanza-unico-1106", projectId: "avanza-unico", code: "1106", floor: "11", type: "Tipología a confirmar", bedrooms: -1, ownM2: 0, balconyM2: 0, totalM2: 0, currency: "USD", price: 64000, parking: -1, status: "Disponible", features: [...staleAvailability, "Tipología, superficie y cochera pendientes"], updatedAt: collectionUpdatedAt, imageUrl: image("17w-V-TpHXlscNfkbjIWsa576ljVmpsDa") },
  { id: "avanza-in-1302", projectId: "avanza-in-1362", code: "1302", floor: "13", type: "Monoambiente", bedrooms: 0, ownM2: 32, balconyM2: 0, totalM2: 32, currency: "USD", price: 60000, parking: 1, status: "Disponible", features: [...staleAvailability, "Superficie y cochera requieren confirmación final"], updatedAt: collectionUpdatedAt, imageUrl: image("1joBxzma663h0f2AgKjr80Z07Y3dza1Ud") },
  { id: "avanza-houze-306", projectId: "avanza-houze", code: "306", floor: "3", type: "Monoambiente", bedrooms: 0, ownM2: 39.9, balconyM2: 0, totalM2: 39.9, currency: "USD", price: 74250, parking: 1, status: "Disponible", features: [...staleAvailability, "Superficie y cochera requieren confirmación final"], updatedAt: collectionUpdatedAt, imageUrl: image("1PNksWnK91QxBDdCN0mw3ItKB4tEAN99l") },
  { id: "avanza-houze-308", projectId: "avanza-houze", code: "308", floor: "3", type: "Monoambiente", bedrooms: 0, ownM2: 39.9, balconyM2: 0, totalM2: 39.9, currency: "USD", price: 79200, parking: 1, status: "Disponible", features: [...staleAvailability, "Superficie y cochera requieren confirmación final"], updatedAt: collectionUpdatedAt, imageUrl: image("13yZyWueKc6Ok7P7eI0nUVAC8iNS9-fNw") },
  { id: "avanza-houze-301", projectId: "avanza-houze", code: "301", floor: "3", type: "Monoambiente", bedrooms: 0, ownM2: 39.9, balconyM2: 0, totalM2: 39.9, currency: "USD", price: 81000, parking: 1, status: "Disponible", features: [...staleAvailability, "Superficie y cochera requieren confirmación final"], updatedAt: collectionUpdatedAt, imageUrl: image("1VkufCsQfqdLgVMGBi30T4y4XaLCQLfEv") },
];
